### ISSUE TITLE
hi i download the zip

### ISSUE THREAD

**Issue by evelyn0918** [gzebec/APEX-Dynamic-Marquee#1]
hi i download zip but i cant  import region_type_plugin_com_oracle_apex_dynamic_marquee of Database Application, Page or Component Export

**Comment by gzebec** [comment]
> hi i download zip but i cant import region_type_plugin_com_oracle_apex_dynamic_marquee of Database Application, Page or Component Export

hi Evelyn.
the source allows only two column source (E.g. select tag, url from your_tag_table).
Can you please attach an error.

**Comment by evelyn0918** [comment]
Thanks for your response
I use oracle free workspace，maybe  workspace wrong
<img width="794" alt="未命名" src="https://user-images.githubusercontent.com/63397876/78884416-74656180-7a8d-11ea-85b9-e76be0c4362f.png">
<img width="790" alt="未命名2" src="https://user-images.githubusercontent.com/63397876/78884500-9d85f200-7a8d-11ea-9f39-01e6cfc6ec9c.png">

**Comment by gzebec** [comment]
> Thanks for your response
> I use oracle free workspace，maybe workspace wrong
> <img alt="未命名" width="794" src="https://user-images.githubusercontent.com/63397876/78884416-74656180-7a8d-11ea-85b9-e76be0c4362f.png">
> <img alt="未命名2" width="790" src="https://user-images.githubusercontent.com/63397876/78884500-9d85f200-7a8d-11ea-9f39-01e6cfc6ec9c.png">

This is a plugin. You need tu upload a plugin.
![image](https://user-images.githubusercontent.com/22852677/78885627-39e3d080-7a5d-11ea-9c6a-145d7600c98d.png)
You are trying to upload a plugin as application. That's not going to work.

**Comment by evelyn0918** [comment]
its working ，thank you

**Comment by gzebec** [comment]
> its working ，thank you

You're welcome.
